#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     rtMotor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     ltMotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//
// As a driver I use the right joystick to control the robot.
//
// ROBOT
//  Use the gyro in NXT3, LtMotor in Motor2, RtMotor in Motor1
//
#include "JoystickDriver.c"
#include "i_debug.c"
#include "i_deadzone.c"
#include "i_lookup.c"

#pragma DebuggerWindows("joystickSimple");
int count=0;
int timeLeft=0; // A global variable that sticks around each frame
int gyroBias=0;

// ==================Foreground Task ==========================//
// Run every second
#define FOREGROUND_MS 50
task main(){
//---------------------------END INIT-------------------------------//
	while(true){
		clearTimer(T1);
		hogCPU(); //Prevent other tasks from running when this one is.
		//writeDebugStreamLine("Foreground\n"); //Let me know when the foreground runs
	  count=count+1; // Count the number of times the foreground runs.

	  //--------------------------FOREGROUND------------------------------------//
		int jstickX = 0;
		int jstickY = 0;

		// ------- Joystick Control --------//
		getJoystickSettings(joystick);

		jstickX = Lookup1(joystick.joy1_x2);
		jstickY = Lookup1(joystick.joy1_y2);

		// ------- Control the drive motors ----------//
		motor[ltMotor]=(jstickY + jstickX);
		motor[rtMotor]=(jstickY - jstickX);

		if(joy1Btn(1))                  // If Joy1-Button1 is pressed:
    {
    	servo[servo1]=255;              // Turn Motor A On at full power
    }
    else                            // If Joy1-Button1 is NOT pressed:
    {
    	servo[servo1]=200;              // Turn Motor A Off
    }

	  //--------------------------END FOREGROUND--------------------------------//
		DebugPrint();

		timeLeft=FOREGROUND_MS-time1[T1]; // Calculate the time used in the foreground
	  releaseCPU(); // Let other tasks run now.
	  wait1Msec(timeLeft);// The time other tasks have to run before foreground takes control.
	}// While Loop
}// Foreground Main Task*/
